# Generated by Django 4.1.7 on 2023-04-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="body",
            field=models.TextField(max_length=5000),
        ),
    ]
